#!/bin/tcsh -f  

echo " *********        ****       ***      **     ****         ****                "
echo " **     **       **  **      ****     **     ** **       **  **               "
echo " **     **      **    **     ** **    **     **  **     **    **              " 
echo " *********     **      **    **  **   **     **   **   **      **             " 
echo " **            **********    **   **  **     **  **    **********             "
echo " **            **      **    **    ** **     ** **     **      **             "
echo " **            **      **    **     ****     ****      **      **             "
echo 
echo " a tcl command created by VISRUAT T R (its pronounced as Vishruth)            "
echo 
echo
echo ""

set my_work_dir = 'pwd'  # setting the working directory as the current path

if ($#argv != 1) then	#if no. of arguements not equal to 1 
	echo "Info: Please provide the csv file" 
	exit 1
endif

if(! -f $argv[1] || $argv[1] == "-help") then #if arg is not a file or arg = "-help"
	if($argv[1] != "-help") then #if arg not "-help"
		echo "Error: Cannot find csv file $argv[1]. Exiting..."
		exit 1
	else
		echo "USAGE: ./panda <csv file> , where the <csv file> consists of 2 columns  -->  1st column is being case sensitive."
		echo "Note if the file is not in the same directory, ensure to include the path along with the <csv file>"
		echo 
		echo "<Design Name> is the name of the top module"
		echo 
		echo "<Output Directory> is the name of the output directory where you want to dump synthesis script, synthesized netlist and timing report" 
		echo 
		echo "<Netlist Directory> is the name of the directory where all RTL netlist are present"
		echo
		echo "<Early Library Path> is the file path of the early cell library to be used for STA"
		echo
		echo "<Late Library Path> is the file path of the late cell library to be used for STA"
		echo
		echo "<Constratints file> is the csv file path of constraints to be used for STA"
		echo
		echo "Exiting...."
		exit 1
	endif
else
		tclsh pandabro.tcl $argv[1]
endif
 
